ERROR 2025-08-27 21:13:16,568 log 16352 14612 Internal Server Error: /api/auth/auth/login/
Traceback (most recent call last):
  File "C:\Users\ModernTech\.virtualenvs\evoting_system-M8NHDx1B\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ModernTech\.virtualenvs\evoting_system-M8NHDx1B\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\ModernTech\.virtualenvs\evoting_system-M8NHDx1B\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\evoting_system-M8NHDx1B\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\ModernTech\.virtualenvs\evoting_system-M8NHDx1B\Lib\site-packages\rest_framework\renderers.py", line 731, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "C:\Users\ModernTech\.virtualenvs\evoting_system-M8NHDx1B\Lib\site-packages\rest_framework\renderers.py", line 662, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "C:\Users\ModernTech\.virtualenvs\evoting_system-M8NHDx1B\Lib\site-packages\rest_framework\renderers.py", line 558, in get_raw_data_form
    serializer = view.get_serializer()
  File "C:\Users\ModernTech\.virtualenvs\evoting_system-M8NHDx1B\Lib\site-packages\rest_framework\generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
  File "C:\Users\ModernTech\.virtualenvs\evoting_system-M8NHDx1B\Lib\site-packages\rest_framework\generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'UserLoginView' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
ERROR 2025-08-27 21:15:16,416 log 9108 12224 Internal Server Error: /api/auth/login/
Traceback (most recent call last):
  File "C:\Users\ModernTech\.virtualenvs\evoting_system-M8NHDx1B\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ModernTech\.virtualenvs\evoting_system-M8NHDx1B\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\ModernTech\.virtualenvs\evoting_system-M8NHDx1B\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\evoting_system-M8NHDx1B\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\ModernTech\.virtualenvs\evoting_system-M8NHDx1B\Lib\site-packages\rest_framework\renderers.py", line 731, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "C:\Users\ModernTech\.virtualenvs\evoting_system-M8NHDx1B\Lib\site-packages\rest_framework\renderers.py", line 662, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "C:\Users\ModernTech\.virtualenvs\evoting_system-M8NHDx1B\Lib\site-packages\rest_framework\renderers.py", line 558, in get_raw_data_form
    serializer = view.get_serializer()
  File "C:\Users\ModernTech\.virtualenvs\evoting_system-M8NHDx1B\Lib\site-packages\rest_framework\generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
  File "C:\Users\ModernTech\.virtualenvs\evoting_system-M8NHDx1B\Lib\site-packages\rest_framework\generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'UserLoginView' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
ERROR 2025-08-30 17:19:27,091 log 12604 8316 Internal Server Error: /api/auth/voter_login/
Traceback (most recent call last):
  File "C:\Users\ModernTech\.virtualenvs\evoting_system-M8NHDx1B\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ModernTech\.virtualenvs\evoting_system-M8NHDx1B\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ModernTech\.virtualenvs\evoting_system-M8NHDx1B\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\evoting_system-M8NHDx1B\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\evoting_system-M8NHDx1B\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ModernTech\.virtualenvs\evoting_system-M8NHDx1B\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\ModernTech\.virtualenvs\evoting_system-M8NHDx1B\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\ModernTech\.virtualenvs\evoting_system-M8NHDx1B\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ModernTech\Desktop\react\django\evoting_system\offline_voting_system\backend\accounts\views.py", line 56, in post
    if not voter.election.is_ongoing:
           ^^^^^
UnboundLocalError: cannot access local variable 'voter' where it is not associated with a value
